### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike-server#18]
Right now JSON is not fully working. This issue is high priority and will be worked on as soon as possible.

- [ ] figure out JSON to EDN serialisation
  - mapping of namespaces
  - keywords
  - symbols
  - datalog
- [ ] hammock for a good solution
- [ ] write an ADR if there are decisions to make
- [ ] implement the solution with reasonable testing

**Comment by alekcz** [comment]
@TimoKramer if I wanted to give this a try where should I start?

**Comment by TimoKramer** [comment]
Hey @alekcz . Thanks for stepping up! I will talk it through with @kordano tomorrow and provide some details.

**Comment by TimoKramer** [comment]
@alekcz We did not evaluate the exact problems we are facing so there might be some coming up on your way in case you take this issue over. Our guessing is, that the problem is mostly with translating JSON data to internal edn as mentioned above. If we figure out some more details we will write it down here.

Thanks again for your involvement!

**Comment by TimoKramer** [comment]
The JSON support being quite sophisticated we should spend some more hammock time on it.

**Comment by alekcz** [comment]
I've thought about this a bit and done research on what the community is doing. I'm ready for hammock time! I'll prepare an RFC in the next 2 weeks. 

For the spec I've drawn some inspiration from [edn-json](https://github.com/wilkerlucio/edn-json#encoding-decisions). 
And I'm thinking implementation should use [jsonista](https://github.com/metosin/jsonista) as it's the fastest gun in the west apparently. 

When the RFC is ready would love to chat and get input
