### ISSUE TITLE
Deciding on License

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike-server#19]
Since cloud providers love to offer opensource software as their own service it might be an idea to switch to a license that does not permit usage as a service offering.
Article discussing that: https://onezero.medium.com/open-source-betrayed-industry-leaders-accuse-amazon-of-playing-a-rigged-game-with-aws-67177bc748b7

**Comment by whilo** [comment]
I think this is a good idea, we cannot change the licence of Datahike though (without reaching out to and getting permission of all contributors).

**Comment by TimoKramer** [comment]
We will stick with permissive open source
