### ISSUE TITLE
API documentation missing 

### ISSUE THREAD

**Issue by jsmassa** [replikativ/datahike-server#23]
So far only the server setup seems to be documented. 
Some documentation on how to use the resulting API would make it easier for developers to program clients for datahike and for people that want to use the REST interface directly.

**Comment by whilo** [comment]
The swagger interface already provides extensive self documentation. What do you think is needed in addition?

(Just out of curiousity, I have not used datahiker-server a lot yet.)

**Comment by jsmassa** [comment]
If that is the case then there should be a note about that in the README.md. I personally do not know about swagger and how to know that there is a swagger interface from the README here. So I went through the source code and the tests which did not show examples for everything. There should definitely be some path from here to find out how to use the API.

**Comment by TimoKramer** [comment]
I will think about adding the swagger to the README, maybe just mention it there or something else.

**Comment by TimoKramer** [comment]
something like that https://bob-cd.github.io/pages/api-reference.html
