### ISSUE TITLE
Switch from dockerhub to GH container registry

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike-server#51]
Docker Hub shuts down OSS-images without registering to some kind of thing or paying. We should just use [GitHub container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) let's see how long we can rely on that...

**Comment by whilo** [comment]
For the Redis backend we also need a redis container btw. For S3 we maybe could use https://min.io/docs/minio/container/index.html, but I think it would be nicer to check against AWS S3 directly.

**Comment by TimoKramer** [comment]
Not needed anymore
